name: "geeki"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: db
    ports:
     - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: cache
    ports:
     - "6379:6379"
    restart: always
