version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONBUFFERED=1
    command: streamlit run src/app.py

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datascience
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql